"""test 23

Revision ID: 07f86ac4a214
Revises: c12b39d048e7
Create Date: 2022-08-19 13:41:16.095237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f86ac4a214'
down_revision = 'c12b39d048e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employes', sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employes', 'sex')
    # ### end Alembic commands ###
