"""test 24

Revision ID: 08330d94e99f
Revises: 07f86ac4a214
Create Date: 2022-08-19 13:48:57.441197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08330d94e99f'
down_revision = '07f86ac4a214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfances',
    sa.Column('enfance_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('prenom', sa.String(length=64), nullable=False),
    sa.Column('date_de_naissance', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenumenfances'), nullable=True),
    sa.Column('parent_1_id', sa.Integer(), nullable=False),
    sa.Column('parent_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_1_id'], ['employes.employe_id'], ),
    sa.ForeignKeyConstraint(['parent_2_id'], ['employes.employe_id'], ),
    sa.PrimaryKeyConstraint('enfance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enfances')
    # ### end Alembic commands ###
