"""test 17

Revision ID: 1445a6f7ec13
Revises: 23ccc2b936cc
Create Date: 2022-08-20 20:02:48.025406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1445a6f7ec13'
down_revision = '23ccc2b936cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_labo_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'clients', ['labo_id'], ['labo_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_labo_id_fkey', 'orders', 'labos', ['labo_id'], ['labo_id'])
    # ### end Alembic commands ###
