"""test 15

Revision ID: 1600d3a2f7dc
Revises: 89c86f59eec1
Create Date: 2022-08-18 17:20:36.559885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1600d3a2f7dc'
down_revision = '89c86f59eec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'enfance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enfances', sa.Column('enfance_id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
