"""test 2

Revision ID: 16dce0a01d1c
Revises: 9f591434275d
Create Date: 2022-08-17 15:48:03.166878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dce0a01d1c'
down_revision = '9f591434275d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveiller_table',
    sa.Column('qui_surveille_autre', sa.Integer(), nullable=True),
    sa.Column('qui_est_surveille', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qui_est_surveille'], ['employes.employe_id'], ),
    sa.ForeignKeyConstraint(['qui_surveille_autre'], ['employes.employe_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveiller_table')
    # ### end Alembic commands ###
