"""test 15

Revision ID: 23ccc2b936cc
Revises: 8ec2f9ebbeb3
Create Date: 2022-08-20 19:25:20.814505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ccc2b936cc'
down_revision = '8ec2f9ebbeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.Column('echantillon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['echantillon_id'], ['echantillons.echantillon_id'], ),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
