"""test 20

Revision ID: 2955c5094592
Revises: 418605289f58
Create Date: 2022-08-19 11:09:04.850915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2955c5094592'
down_revision = '418605289f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfances',
    sa.Column('enfance_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('prenom', sa.String(length=64), nullable=False),
    sa.Column('date_de_naissance', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'autre', name='sexenum'), nullable=False),
    sa.Column('parent_1_id', sa.Integer(), nullable=False),
    sa.Column('parent_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_1_id'], ['employes.employe_id'], ),
    sa.ForeignKeyConstraint(['parent_2_id'], ['employes.employe_id'], ),
    sa.PrimaryKeyConstraint('enfance_id')
    )
    op.alter_column('labos', 'responsable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labos', 'responsable_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('enfances')
    # ### end Alembic commands ###
