"""test 8

Revision ID: 36bc4bf9344d
Revises: a119de0b5f49
Create Date: 2022-08-18 14:25:28.488891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bc4bf9344d'
down_revision = 'a119de0b5f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youngest_child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['youngest_child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labosadresse',
    sa.Column('labos_adresse_id', sa.Integer(), nullable=False),
    sa.Column('labos_adresse', sa.String(length=128), nullable=False),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.PrimaryKeyConstraint('labos_adresse_id')
    )
    op.drop_constraint('labos_supervisor_id_fkey', 'labos', type_='foreignkey')
    op.drop_column('labos', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labos', sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('labos_supervisor_id_fkey', 'labos', 'employes', ['supervisor_id'], ['employe_id'])
    op.drop_table('labosadresse')
    op.drop_table('parents')
    op.drop_table('children')
    # ### end Alembic commands ###
