"""test 21

Revision ID: 5a1fcedae6ce
Revises: c76c70d0cc9d
Create Date: 2022-08-19 11:45:39.982746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1fcedae6ce'
down_revision = 'c76c70d0cc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employes', sa.Column('sex', postgresql.ENUM('Male', 'Female', 'Autre', name='SexEnum'), nullable=True))
    op.add_column('enfances', sa.Column('sex', postgresql.ENUM('Male', 'Female', 'Autre', name='SexEnum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'sex')
    op.drop_column('employes', 'sex')
    # ### end Alembic commands ###
