"""nullable 2

Revision ID: 7dfd3b6fc545
Revises: 8d03f87b2674
Create Date: 2022-08-21 11:31:04.925576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dfd3b6fc545'
down_revision = '8d03f87b2674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'client_nom',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('clients', 'client_prenom',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('clients', 'client_domain',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('clients', 'adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('clients', 'code_postal',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('clients', 'ville',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('clients', 'pays',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('clients', 'labo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('echantillons', 'dossier_ref',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('enfances', 'nom',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('enfances', 'prenom',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('enfances', 'date_de_naissance',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('labos', 'labo_nom',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('labos', 'labo_adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('labos', 'responsable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'labos', ['labo_nom'])
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'echantillon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('point_collectes', 'point_collecte_nom',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('point_collectes', 'point_collecte_adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('point_collectes', 'labo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processus', 'processus_nom',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_unique_constraint(None, 'processus', ['processus_nom'])
    op.alter_column('resultats', 'sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('samples', 'echantillon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('samples', 'samples_ref',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('samples', 'cuve_ref',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'cuve_ref',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('samples', 'samples_ref',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('samples', 'echantillon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resultats', 'sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'processus', type_='unique')
    op.alter_column('processus', 'processus_nom',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('point_collectes', 'labo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('point_collectes', 'point_collecte_adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('point_collectes', 'point_collecte_nom',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('orders', 'echantillon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'labos', type_='unique')
    op.alter_column('labos', 'responsable_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('labos', 'labo_adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('labos', 'labo_nom',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('enfances', 'date_de_naissance',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('enfances', 'prenom',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('enfances', 'nom',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('echantillons', 'dossier_ref',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('clients', 'labo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'pays',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('clients', 'ville',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('clients', 'code_postal',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('clients', 'adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('clients', 'client_domain',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('clients', 'client_prenom',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('clients', 'client_nom',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
