"""test 26

Revision ID: 7ec98f32aa4c
Revises: b45711752a26
Create Date: 2022-08-19 15:04:55.580296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec98f32aa4c'
down_revision = 'b45711752a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=40), nullable=True),
    sa.Column('lname', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_nom', sa.String(length=64), nullable=False),
    sa.Column('client_prenom', sa.String(length=64), nullable=False),
    sa.Column('client_domain', sa.String(length=64), nullable=False),
    sa.Column('adresse', sa.String(length=128), nullable=False),
    sa.Column('code_postal', sa.String(length=128), nullable=False),
    sa.Column('ville', sa.String(length=128), nullable=False),
    sa.Column('pays', sa.String(length=64), nullable=False),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_domain')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('clients_test')
    # ### end Alembic commands ###
