"""test 12

Revision ID: 8752b4aed6b4
Revises: 36bc4bf9344d
Create Date: 2022-08-18 15:01:23.623101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8752b4aed6b4'
down_revision = '36bc4bf9344d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('labo_adresse_id', sa.Integer(), nullable=False),
    sa.Column('labo_adresse', sa.String(length=128), nullable=True),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.PrimaryKeyConstraint('labo_adresse_id')
    )
    op.drop_constraint('labos_supervisor_id_fkey', 'labos', type_='foreignkey')
    op.drop_column('labos', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labos', sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('labos_supervisor_id_fkey', 'labos', 'employes', ['supervisor_id'], ['employe_id'])
    op.drop_table('adresse')
    # ### end Alembic commands ###
