"""test 21

Revision ID: 87c0f927862a
Revises: 077c64df3381
Create Date: 2022-08-20 23:18:56.060348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c0f927862a'
down_revision = '077c64df3381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultats',
    sa.Column('resultat_id', sa.Integer(), nullable=False),
    sa.Column('resultat_date', sa.DateTime(), nullable=False),
    sa.Column('degree', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('resultat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultats')
    # ### end Alembic commands ###
