"""nullable 1

Revision ID: 8d03f87b2674
Revises: 87c0f927862a
Create Date: 2022-08-21 10:56:57.835648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d03f87b2674'
down_revision = '87c0f927862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employes', 'nom',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('employes', 'prenom',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('employes', 'date_de_naissance',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('employes', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', 'Autre', name='sexenumemployes'),
               nullable=False)
    op.alter_column('employes', 'adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('employes', 'labo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employes', 'labo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employes', 'adresse',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('employes', 'sex',
               existing_type=postgresql.ENUM('Male', 'Female', 'Autre', name='sexenumemployes'),
               nullable=True)
    op.alter_column('employes', 'date_de_naissance',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('employes', 'prenom',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('employes', 'nom',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
