"""test 8

Revision ID: 8ec2f9ebbeb3
Revises: 5cf17fbda3e9
Create Date: 2022-08-20 17:00:39.158827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec2f9ebbeb3'
down_revision = '5cf17fbda3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('echantillons',
    sa.Column('echantillon_id', sa.Integer(), nullable=False),
    sa.Column('dossier_ref', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('echantillon_id')
    )
    op.create_table('samples',
    sa.Column('samples_id', sa.Integer(), nullable=False),
    sa.Column('echantillon_id', sa.Integer(), nullable=True),
    sa.Column('samples_ref', sa.String(length=32), nullable=True),
    sa.Column('cuve_ref', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['echantillon_id'], ['echantillons.echantillon_id'], ),
    sa.PrimaryKeyConstraint('samples_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    op.drop_table('echantillons')
    # ### end Alembic commands ###
