"""test 30

Revision ID: 8ef77bdfd769
Revises: 4734b6c5183d
Create Date: 2022-08-19 15:59:54.203241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef77bdfd769'
down_revision = '4734b6c5183d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employes',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=32), nullable=True),
    sa.Column('prenom', sa.String(length=32), nullable=True),
    sa.Column('date_de_naissance', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenumemployes'), nullable=True),
    sa.Column('adresse', sa.String(length=128), nullable=True),
    sa.Column('salaire', sa.Float(), nullable=True),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.Column('surveille_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.ForeignKeyConstraint(['surveille_id'], ['employes.employe_id'], ),
    sa.PrimaryKeyConstraint('employe_id')
    )
    op.create_table('enfances',
    sa.Column('enfance_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('prenom', sa.String(length=64), nullable=True),
    sa.Column('date_de_naissance', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenumenfances'), nullable=True),
    sa.PrimaryKeyConstraint('enfance_id')
    )
    op.create_table('labos',
    sa.Column('labo_id', sa.Integer(), nullable=False),
    sa.Column('labo_nom', sa.String(length=32), nullable=True),
    sa.Column('labo_adresse', sa.String(length=128), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['employes.employe_id'], ),
    sa.PrimaryKeyConstraint('labo_id')
    )
    op.create_table('point_collectes',
    sa.Column('point_collecte_id', sa.Integer(), nullable=False),
    sa.Column('point_collecte_nom', sa.String(length=128), nullable=True),
    sa.Column('point_collecte_adresse', sa.String(length=128), nullable=True),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.PrimaryKeyConstraint('point_collecte_id')
    )
    op.create_foreign_key(None, 'clients', 'labos', ['labo_id'], ['labo_id'])
    op.create_foreign_key(None, 'employes_enfances', 'enfances', ['enfance_id'], ['enfance_id'])
    op.create_foreign_key(None, 'employes_enfances', 'employes', ['employe_id'], ['employe_id'])
    op.create_foreign_key(None, 'employes_processus', 'employes', ['employe_id'], ['employe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employes_processus', type_='foreignkey')
    op.drop_constraint(None, 'employes_enfances', type_='foreignkey')
    op.drop_constraint(None, 'employes_enfances', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_table('point_collectes')
    op.drop_table('labos')
    op.drop_table('enfances')
    op.drop_table('employes')
    # ### end Alembic commands ###
