"""test 22

Revision ID: 986ac4d85223
Revises: 5a1fcedae6ce
Create Date: 2022-08-19 11:58:52.740488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986ac4d85223'
down_revision = '5a1fcedae6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employes', sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenumemployes'), nullable=True))
    op.add_column('enfances', sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenumenfances'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'sex')
    op.drop_column('employes', 'sex')
    # ### end Alembic commands ###
