"""test 16

Revision ID: a1674b239e6c
Revises: a18079031ff8
Create Date: 2022-08-18 17:33:03.318125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1674b239e6c'
down_revision = 'a18079031ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enfances', sa.Column('enfance_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'enfance_id')
    # ### end Alembic commands ###
