"""test 16

Revision ID: a18079031ff8
Revises: 1600d3a2f7dc
Create Date: 2022-08-18 17:32:15.311361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18079031ff8'
down_revision = '1600d3a2f7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enfances', sa.Column('enfance_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'enfance_id')
    # ### end Alembic commands ###
