"""test 19

Revision ID: a43c3858cf5c
Revises: 1445a6f7ec13
Create Date: 2022-08-20 22:57:38.185262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43c3858cf5c'
down_revision = '1445a6f7ec13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_labo_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'labo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('labo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_labo_id_fkey', 'orders', 'labos', ['labo_id'], ['labo_id'])
    # ### end Alembic commands ###
