"""test 13

Revision ID: a84e14ca880d
Revises: 8752b4aed6b4
Create Date: 2022-08-18 15:13:03.063530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84e14ca880d'
down_revision = '8752b4aed6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_collecte',
    sa.Column('point_collecte_id', sa.Integer(), nullable=False),
    sa.Column('point_collecte_adresse', sa.String(length=128), nullable=True),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], ),
    sa.PrimaryKeyConstraint('point_collecte_id')
    )
    op.drop_table('adresse')
    op.add_column('labos', sa.Column('labo_adresse', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labos', 'labo_adresse')
    op.create_table('adresse',
    sa.Column('labo_adresse_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('labo_adresse', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('labo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labos.labo_id'], name='adresse_labo_id_fkey'),
    sa.PrimaryKeyConstraint('labo_adresse_id', name='adresse_pkey')
    )
    op.drop_table('point_collecte')
    # ### end Alembic commands ###
