"""test 6

Revision ID: b42cd0722256
Revises: d6d1815db0c0
Create Date: 2022-08-17 22:44:06.877669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b42cd0722256'
down_revision = 'd6d1815db0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processus',
    sa.Column('processus_id', sa.Integer(), nullable=False),
    sa.Column('processus_nom', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('processus_id')
    )
    op.create_table('employes_processus',
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('processus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.employe_id'], ),
    sa.ForeignKeyConstraint(['processus_id'], ['processus.processus_id'], )
    )
    op.drop_column('labos', 'date_deput')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labos', sa.Column('date_deput', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_table('employes_processus')
    op.drop_table('processus')
    # ### end Alembic commands ###
