"""test 25

Revision ID: b45711752a26
Revises: 08330d94e99f
Create Date: 2022-08-19 14:26:33.682416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45711752a26'
down_revision = '08330d94e99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employes_enfances',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('enfance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.employe_id'], ),
    sa.ForeignKeyConstraint(['enfance_id'], ['enfances.enfance_id'], ),
    sa.PrimaryKeyConstraint('employe_id', 'enfance_id')
    )
    op.drop_constraint('enfances_parent_1_id_fkey', 'enfances', type_='foreignkey')
    op.drop_constraint('enfances_parent_2_id_fkey', 'enfances', type_='foreignkey')
    op.drop_column('enfances', 'parent_1_id')
    op.drop_column('enfances', 'parent_2_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enfances', sa.Column('parent_2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enfances', sa.Column('parent_1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('enfances_parent_2_id_fkey', 'enfances', 'employes', ['parent_2_id'], ['employe_id'])
    op.create_foreign_key('enfances_parent_1_id_fkey', 'enfances', 'employes', ['parent_1_id'], ['employe_id'])
    op.drop_table('employes_enfances')
    # ### end Alembic commands ###
