"""test 22

Revision ID: c12b39d048e7
Revises: 986ac4d85223
Create Date: 2022-08-19 12:04:28.034668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12b39d048e7'
down_revision = '986ac4d85223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enfances', sa.Column('sex', sa.Enum('Male', 'Female', 'Autre', name='sexenumenfances'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'sex')
    # ### end Alembic commands ###
