"""test 21

Revision ID: c76c70d0cc9d
Revises: fd1cb9c2aab0
Create Date: 2022-08-19 11:39:31.769927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c76c70d0cc9d'
down_revision = 'fd1cb9c2aab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employes', sa.Column('sex', postgresql.ENUM('Male', 'Female', 'Autre', name='sex'), nullable=True))
    op.add_column('enfances', sa.Column('sex', postgresql.ENUM('Male', 'Female', 'Autre', name='sex'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enfances', 'sex')
    op.drop_column('employes', 'sex')
    # ### end Alembic commands ###
