"""test 17

Revision ID: f3e00f6b787f
Revises: a1674b239e6c
Create Date: 2022-08-18 17:43:02.651211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e00f6b787f'
down_revision = 'a1674b239e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfances',
    sa.Column('enfance_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('prenom', sa.String(length=64), nullable=False),
    sa.Column('date_de_naissance', sa.DateTime(), nullable=True),
    sa.Column('parent_1_id', sa.Integer(), nullable=False),
    sa.Column('parent_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_1_id'], ['employes.employe_id'], ),
    sa.ForeignKeyConstraint(['parent_2_id'], ['employes.employe_id'], ),
    sa.PrimaryKeyConstraint('enfance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enfances')
    # ### end Alembic commands ###
