"""test 19

Revision ID: ff29456bed96
Revises: f3e00f6b787f
Create Date: 2022-08-19 09:58:39.567184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff29456bed96'
down_revision = 'f3e00f6b787f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labos', sa.Column('responsable_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'labos', 'employes', ['responsable_id'], ['employe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labos', type_='foreignkey')
    op.drop_column('labos', 'responsable_id')
    # ### end Alembic commands ###
